config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'login', to: 'users#login'
  post 'loginCheck', to: 'users#checkCredentials'

  resources :users do
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

    def index
        @customID = params[:user_id]
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def new
    end

    def create
        @article = Article.new(article_params)
        @article.save
        redirect_to @article
    end

    def update
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
       
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text, :summary)
        end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end

    def checkCredentials
        @user = User.where(email: params[:user][:email]).first
        

        if @user.present?
            pw = @user.password_digest == params[:user][:password_digest] ? true : false
            if pw
                redirect_to user_articles_path(@user.id), id: @user.id
            else
                flash[:danger] = 'Incorrect Login Credentials'
                redirect_to root_path
            end
        else
            flash[:danger] = 'Incorrect Login Credentials'
            redirect_to root_path
        end

        # render json: {
        #     data: @user.present?
        # }
    end

    def create
        @user = User.new(user_params)

        @user.save
        flash[:success] = 'Successfully Registered'
        redirect_to root_path
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :password_digest)
        end

    private
        def user_email_params
            params.require(:user).permit(:email, :email)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :Details %><br>
    <%= form.text_area :summary %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
 
<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Details</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.summary %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<script>
localStorage.setItem("number",<%= @customID %>)
</script>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.label :Details %><br>
      <%= form.text_area :summary %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

  <%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Description:</strong>
<%= @article.text %>
</p>

<p>
<strong>Details:</strong>
<%= @article.summary %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Delete Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login.html.erb
<%= form_with scope: :user, url: '/loginCheck', local: true do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.email_field  :email %>
    </p>
   
    <p>
      <%= form.label :password %><br>
      <%= form.password_field  :password_digest %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

  <%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<% flash.each do |key, value| %>
  <h1 class="alert alert-<%= key %>"><%= value %></h1>
<% end %>

<%= form_with scope: :user, url: users_path, local: true do |form| %>
    
    <p>
      <%= form.label :username %><br>
      <%= form.text_field :username %>
    </p>

    <p>
      <%= form.label :email %><br>
      <%= form.email_field  :email %>
    </p>
   
    <p>
      <%= form.label :password %><br>
      <%= form.password_field  :password_digest %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

  <%= link_to 'Back', root_path %>

app/views/welcome/index.html.erb
<% flash.each do |key, value| %>
    <h1 class="alert alert-<%= key %>"><%= value %></h1>
<% end %>
<h1>Hello, Rails!</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Details</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.summary %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Register', new_user_path %>
<%= link_to 'Login', '/login' %>

<%-# comment here -%>
<%-# link_to 'My Blog', controller: 'articles' -%>